"""initial schema

Revision ID: 41d67dc67154
Revises: 
Create Date: 2026-08-30 23:57:14.403245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy as pgvector_sa

# revision identifiers, used by Alembic.
revision: str = '41d67dc67154'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check whether the pgvector extension is available on this Postgres
    # instance before trying to create it. This avoids aborting the
    # transaction when the extension isn't installed (e.g. local dev).
    _has_vector = bool(
        op.get_bind().execute(
            sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'")
        ).scalar()
    )
    if _has_vector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    else:
        print("WARNING: pgvector extension not available — embedding column will use TEXT fallback")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_login_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('external_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_user_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities')),
    sa.UniqueConstraint('provider', 'external_user_id', name=op.f('uq_external_identities_provider'))
    )
    op.create_index('ix_external_identity_user', 'external_identities', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workspaces_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_workspaces_organization_id'))
    )
    op.create_index('ix_workspaces_org_created', 'workspaces', ['organization_id', 'created_at'], unique=False)
    op.create_table('escalation_rules',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_escalation_rules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_rules'))
    )
    op.create_index('ix_escalation_rules_workspace_priority', 'escalation_rules', ['workspace_id', 'enabled', 'priority'], unique=False)
    op.create_table('integrations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('RECALL', 'GITHUB', 'JIRA', 'LINEAR', 'GOOGLE_CALENDAR', 'MICROSOFT_CALENDAR', 'SLACK', 'NOTION', name='integration_provider'), nullable=False),
    sa.Column('state', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='integration_state'), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_integrations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('workspace_id', 'provider', 'external_account_id', name=op.f('uq_integrations_workspace_id'))
    )
    op.create_index('ix_integrations_workspace_provider', 'integrations', ['workspace_id', 'provider'], unique=False)
    op.create_table('meetings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_MEET', 'ZOOM', 'MICROSOFT_TEAMS', 'SLACK_HUDDLE', name='meeting_provider'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('recall_bot_id', sa.String(length=100), nullable=True),
    sa.Column('join_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'JOINING', 'IN_PROGRESS', 'ENDED', 'FAILED', name='meeting_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_meetings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings')),
    sa.UniqueConstraint('recall_bot_id', name=op.f('uq_meetings_recall_bot_id'))
    )
    op.create_index('ix_meetings_provider_external', 'meetings', ['provider', 'external_id'], unique=False)
    op.create_index('ix_meetings_workspace_status_scheduled', 'meetings', ['workspace_id', 'status', 'scheduled_at'], unique=False)
    op.create_table('memory_episodes',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('speaker', sa.String(length=200), nullable=False),
    sa.Column('speaker_role', sa.Enum('FOUNDER', 'ENGINEER', 'MARKETER', 'MANAGER', 'ASSISTANT', 'OTHER', name='memory_episode_speaker_role'), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memory_episodes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_episodes')),
    sa.UniqueConstraint('workspace_id', 'episode_id', name=op.f('uq_memory_episodes_workspace_id'))
    )
    op.create_index(op.f('ix_memory_episodes_episode_id'), 'memory_episodes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_memory_episodes_workspace_id'), 'memory_episodes', ['workspace_id'], unique=False)
    op.create_table('memory_facts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('predicate', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('fact_kind', sa.Enum('FACT', 'SKILL', 'STATUS_UPDATE', 'COMMITMENT', 'BLOCKER', 'DECISION', 'REQUIREMENT', 'IDEA', 'RISK', 'PERFORMANCE', 'AVAILABILITY', 'PREFERENCE', 'RELATIONSHIP', 'IDENTITY', name='memory_fact_kind'), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=False),
    sa.Column('temporal_hint', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.String(length=32), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('speaker_role', sa.Enum('FOUNDER', 'ENGINEER', 'MARKETER', 'MANAGER', 'ASSISTANT', 'OTHER', name='memory_speaker_role'), nullable=False),
    sa.Column('episode_id', sa.String(length=128), nullable=True),
    sa.Column('temporal_status', sa.Enum('CURRENT', 'SUPERSEDED', 'INVALIDATED', name='memory_temporal_status'), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector_sa.VECTOR(dim=384) if _has_vector else sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memory_facts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_facts')),
    sa.UniqueConstraint('workspace_id', 'fact_id', 'temporal_status', name=op.f('uq_memory_facts_workspace_id'))
    )
    op.create_index(op.f('ix_memory_facts_episode_id'), 'memory_facts', ['episode_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_fact_id'), 'memory_facts', ['fact_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_project'), 'memory_facts', ['project'], unique=False)
    op.create_index('ix_memory_facts_project_kind', 'memory_facts', ['workspace_id', 'project', 'fact_kind'], unique=False)
    op.create_index('ix_memory_facts_subject', 'memory_facts', ['workspace_id', 'subject'], unique=False)
    op.create_index(op.f('ix_memory_facts_workspace_id'), 'memory_facts', ['workspace_id'], unique=False)
    op.create_table('memory_people',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('FOUNDER', 'ENGINEER', 'MARKETER', 'MANAGER', 'DESIGNER', 'OTHER', name='memory_person_role'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_technical', sa.Boolean(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('availability_hours_per_week', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('resume_summary', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_people_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memory_people_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_people')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_memory_people_workspace_id'))
    )
    op.create_index('ix_memory_people_role', 'memory_people', ['workspace_id', 'role'], unique=False)
    op.create_index(op.f('ix_memory_people_workspace_id'), 'memory_people', ['workspace_id'], unique=False)
    op.create_table('memory_projects',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='memory_project_status'), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memory_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_projects')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_memory_projects_workspace_id'))
    )
    op.create_index('ix_memory_projects_status', 'memory_projects', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_memory_projects_workspace_id'), 'memory_projects', ['workspace_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('provider', sa.Enum('RECALL', 'GITHUB', 'JIRA', 'LINEAR', 'GOOGLE_CALENDAR', 'MICROSOFT_CALENDAR', 'SLACK', 'NOTION', name='oauth_state_provider'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_oauth_states_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state', name=op.f('uq_oauth_states_state'))
    )
    op.create_index('ix_oauth_state_expiry', 'oauth_states', ['expires_at'], unique=False)
    op.create_table('payment_orders',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_orders_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_payment_orders_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_orders')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('uq_payment_orders_razorpay_order_id'))
    )
    op.create_index('ix_payment_orders_razorpay_order', 'payment_orders', ['razorpay_order_id'], unique=False)
    op.create_index('ix_payment_orders_workspace', 'payment_orders', ['workspace_id'], unique=False)
    op.create_table('pm_chat_messages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pm_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pm_chat_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pm_chat_messages'))
    )
    op.create_index('ix_pm_chat_workspace_user_created', 'pm_chat_messages', ['workspace_id', 'user_id', 'created_at'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_weekly_reports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reports'))
    )
    op.create_index('ix_reports_workspace_period', 'weekly_reports', ['workspace_id', 'period_start'], unique=True)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_members_workspace_id'))
    )
    op.create_index('ix_members_user_workspace', 'workspace_members', ['user_id', 'workspace_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_calendar_events_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_calendar_events_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    sa.UniqueConstraint('integration_id', 'external_id', name=op.f('uq_calendar_events_integration_id'))
    )
    op.create_index('ix_calendar_owner_starts', 'calendar_events', ['owner_id', 'starts_at'], unique=False)
    op.create_table('decisions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_decisions_meeting_id_meetings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_decisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_workspace_created', 'decisions', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_table('github_repos',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('github_node_id', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('default_branch', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_github_repos_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_repos')),
    sa.UniqueConstraint('integration_id', 'github_node_id', name=op.f('uq_github_repos_integration_id'))
    )
    op.create_index('ix_repos_integration_active', 'github_repos', ['integration_id', 'is_active'], unique=False)
    op.create_table('insights',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('weekly_report_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_reports.id'], name=op.f('fk_insights_weekly_report_id_weekly_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insights_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index('ix_insights_workspace_key_created', 'insights', ['workspace_id', 'key', 'created_at'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_participant_id', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_participants_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_participants')),
    sa.UniqueConstraint('meeting_id', 'external_participant_id', name=op.f('uq_meeting_participants_meeting_id'))
    )
    op.create_index('ix_participants_meeting_user', 'meeting_participants', ['meeting_id', 'user_id'], unique=False)
    op.create_table('memory_tasks',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('assignee_person_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', name='memory_task_status'), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_days', sa.Float(), nullable=True),
    sa.Column('deadline', sa.String(length=32), nullable=True),
    sa.Column('source_fact_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_person_id'], ['memory_people.id'], name=op.f('fk_memory_tasks_assignee_person_id_memory_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['memory_projects.id'], name=op.f('fk_memory_tasks_project_id_memory_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memory_tasks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_tasks'))
    )
    op.create_index('ix_memory_tasks_project', 'memory_tasks', ['workspace_id', 'project_id'], unique=False)
    op.create_index('ix_memory_tasks_status', 'memory_tasks', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_memory_tasks_workspace_id'), 'memory_tasks', ['workspace_id'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_oauth_credentials_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_credentials')),
    sa.UniqueConstraint('integration_id', name=op.f('uq_oauth_credentials_integration_id'))
    )
    op.create_index('ix_oauth_expiry', 'oauth_credentials', ['expires_at'], unique=False)
    op.create_table('payments',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_signature', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], name=op.f('fk_payments_order_id_payment_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_payments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('razorpay_payment_id', name=op.f('uq_payments_razorpay_payment_id'))
    )
    op.create_index('ix_payments_razorpay_payment', 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index('ix_payments_workspace', 'payments', ['workspace_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('recall_transcript_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_transcripts_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('meeting_id', name=op.f('uq_transcripts_meeting_id')),
    sa.UniqueConstraint('recall_transcript_id', name=op.f('uq_transcripts_recall_transcript_id'))
    )
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_webhook_events_meeting_id_meetings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'event_id', name=op.f('uq_webhook_events_provider'))
    )
    op.create_index('ix_webhook_unprocessed', 'webhook_events', ['provider', 'processed_at', 'received_at'], unique=False)
    op.create_table('github_activities',
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_github_activities_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['github_repos.id'], name=op.f('fk_github_activities_repo_id_github_repos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_activities')),
    sa.UniqueConstraint('repo_id', 'external_id', name=op.f('uq_github_activities_repo_id'))
    )
    op.create_index('ix_github_activity_actor_occurred', 'github_activities', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_github_activity_repo_occurred', 'github_activities', ['repo_id', 'occurred_at'], unique=False)
    op.create_table('meeting_extractions',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_meeting_extractions_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_extractions')),
    sa.UniqueConstraint('transcript_id', name=op.f('uq_meeting_extractions_transcript_id'))
    )
    op.create_index('ix_extractions_status_created', 'meeting_extractions', ['status', 'created_at'], unique=False)
    op.create_table('speakers',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('provider_speaker_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_speakers_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_participants.id'], name=op.f('fk_speakers_participant_id_meeting_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakers')),
    sa.UniqueConstraint('meeting_id', 'provider_speaker_id', name=op.f('uq_speakers_meeting_id'))
    )
    op.create_table('tasks',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='task_state'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('execution_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_tasks_decision_id_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tasks_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tasks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_owner_state_due', 'tasks', ['owner_id', 'state', 'due_at'], unique=False)
    op.create_index('ix_tasks_workspace_state_due', 'tasks', ['workspace_id', 'state', 'due_at'], unique=False)
    op.create_table('escalations',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('escalated_to_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], name=op.f('fk_escalations_escalated_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_escalations_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    op.create_index('ix_escalations_task_open', 'escalations', ['task_id', 'resolved_at'], unique=False)
    op.create_table('external_task_mappings',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('external_key', sa.String(length=100), nullable=True),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_external_task_mappings_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_external_task_mappings_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_task_mappings')),
    sa.UniqueConstraint('integration_id', 'external_id', name=op.f('uq_external_task_mappings_integration_id')),
    sa.UniqueConstraint('task_id', 'integration_id', name=op.f('uq_external_task_mappings_task_id'))
    )
    op.create_index('ix_mappings_integration_sync', 'external_task_mappings', ['integration_id', 'last_synced_at'], unique=False)
    op.create_table('reminders',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='delivery_status'), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_reminders_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_reminders_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('task_id', 'body_hash', name=op.f('uq_reminders_task_id'))
    )
    op.create_index('ix_reminders_pending_schedule', 'reminders', ['status', 'scheduled_for'], unique=False)
    op.create_index('ix_reminders_task_created', 'reminders', ['task_id', 'created_at'], unique=False)
    op.create_table('task_activity_matches',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('github_activity_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['github_activity_id'], ['github_activities.id'], name=op.f('fk_task_activity_matches_github_activity_id_github_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_activity_matches_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_activity_matches')),
    sa.UniqueConstraint('task_id', 'github_activity_id', name=op.f('uq_task_activity_matches_task_id'))
    )
    op.create_index('ix_matches_task_confidence', 'task_activity_matches', ['task_id', 'confidence'], unique=False)
    op.create_table('task_candidates',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=True),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'AUTO_APPROVED', 'APPROVED', 'EDITED', 'REJECTED', 'MATERIALIZED', name='candidate_state'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['meeting_extractions.id'], name=op.f('fk_task_candidates_extraction_id_meeting_extractions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_task_candidates_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_task_candidates_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_candidates_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_task_candidates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_candidates')),
    sa.UniqueConstraint('workspace_id', 'extraction_id', 'ref', name=op.f('uq_task_candidates_workspace_id'))
    )
    op.create_index('ix_candidates_workspace_state', 'task_candidates', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_table('task_comments',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_task_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_comments_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comments'))
    )
    op.create_index('ix_comments_task_created', 'task_comments', ['task_id', 'created_at'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name=op.f('uq_task_dependencies_task_id'))
    )
    op.create_table('task_status_history',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('from_state', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='task_state_history'), nullable=True),
    sa.Column('to_state', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='task_state_history_new'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_task_status_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_status_history_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_status_history'))
    )
    op.create_index('ix_task_history_task_created', 'task_status_history', ['task_id', 'created_at'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=True),
    sa.Column('provider_utterance_id', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_ms', sa.Integer(), nullable=True),
    sa.Column('ended_ms', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_transcript_chunks_speaker_id_speakers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_transcript_chunks_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_chunks')),
    sa.UniqueConstraint('transcript_id', 'provider_utterance_id', name=op.f('uq_transcript_chunks_transcript_id'))
    )
    op.create_index('ix_chunks_transcript_sequence', 'transcript_chunks', ['transcript_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_transcript_sequence', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index('ix_task_history_task_created', table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_table('task_dependencies')
    op.drop_index('ix_comments_task_created', table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index('ix_candidates_workspace_state', table_name='task_candidates')
    op.drop_table('task_candidates')
    op.drop_index('ix_matches_task_confidence', table_name='task_activity_matches')
    op.drop_table('task_activity_matches')
    op.drop_index('ix_reminders_task_created', table_name='reminders')
    op.drop_index('ix_reminders_pending_schedule', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_mappings_integration_sync', table_name='external_task_mappings')
    op.drop_table('external_task_mappings')
    op.drop_index('ix_escalations_task_open', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_tasks_workspace_state_due', table_name='tasks')
    op.drop_index('ix_tasks_owner_state_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('speakers')
    op.drop_index('ix_extractions_status_created', table_name='meeting_extractions')
    op.drop_table('meeting_extractions')
    op.drop_index('ix_github_activity_repo_occurred', table_name='github_activities')
    op.drop_index('ix_github_activity_actor_occurred', table_name='github_activities')
    op.drop_table('github_activities')
    op.drop_index('ix_webhook_unprocessed', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('transcripts')
    op.drop_index('ix_payments_workspace', table_name='payments')
    op.drop_index('ix_payments_razorpay_payment', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_oauth_expiry', table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_memory_tasks_workspace_id'), table_name='memory_tasks')
    op.drop_index('ix_memory_tasks_status', table_name='memory_tasks')
    op.drop_index('ix_memory_tasks_project', table_name='memory_tasks')
    op.drop_table('memory_tasks')
    op.drop_index('ix_participants_meeting_user', table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index('ix_insights_workspace_key_created', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_repos_integration_active', table_name='github_repos')
    op.drop_table('github_repos')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_index('ix_decisions_workspace_created', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_calendar_owner_starts', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_members_user_workspace', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_reports_workspace_period', table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index('ix_pm_chat_workspace_user_created', table_name='pm_chat_messages')
    op.drop_table('pm_chat_messages')
    op.drop_index('ix_payment_orders_workspace', table_name='payment_orders')
    op.drop_index('ix_payment_orders_razorpay_order', table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('ix_oauth_state_expiry', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_memory_projects_workspace_id'), table_name='memory_projects')
    op.drop_index('ix_memory_projects_status', table_name='memory_projects')
    op.drop_table('memory_projects')
    op.drop_index(op.f('ix_memory_people_workspace_id'), table_name='memory_people')
    op.drop_index('ix_memory_people_role', table_name='memory_people')
    op.drop_table('memory_people')
    op.drop_index(op.f('ix_memory_facts_workspace_id'), table_name='memory_facts')
    op.drop_index('ix_memory_facts_subject', table_name='memory_facts')
    op.drop_index('ix_memory_facts_project_kind', table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_project'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_fact_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_episode_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_index(op.f('ix_memory_episodes_workspace_id'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_episode_id'), table_name='memory_episodes')
    op.drop_table('memory_episodes')
    op.drop_index('ix_meetings_workspace_status_scheduled', table_name='meetings')
    op.drop_index('ix_meetings_provider_external', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_integrations_workspace_provider', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_escalation_rules_workspace_priority', table_name='escalation_rules')
    op.drop_table('escalation_rules')
    op.drop_index('ix_workspaces_org_created', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_external_identity_user', table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index('ix_audit_org_created', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    # Note: vector extension is not dropped as other DBs may depend on it.
